name: Update Sidebar

on:
  push:
    branches:
      - main

jobs:
  update-sidebar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update script
        run: |
           
           import os 
           
           repo_path = os.listdir()
           files = [f for f in os.listdir(repo_path) if os.path.isfile(os.path.join(repo_path, f))]
           
           print(files)
