name: Update Sidebar

on:
  push:
    branches:
      - main

jobs:
  update-sidebar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update script
        run: |
         python update_sidebar.py
           
           
           
