name: Sidebar Automation

on:
  push:
    branches:
      - main
    ##paths:
      #-  'pages/Testpurpose/*.md'
jobs:
  update-sidebar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Automation Script
        run: |
          python .github/scripts/update_sidebar.py

        env:
          GITHUB_TOKEN: ${{ secrets.testtoken}}
      
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/sidebars/mydoc_sidebar.yml
          git diff --cached --exit-code || git commit -m "Update sidebar"
          git push
